### ISSUE TITLE
Give each ChessPieceType its own class?

### ISSUE THREAD

**Issue by ElwynJohn** [ElwynJohn/Chess#3]

**Comment by rleathart** [comment]
What would be the motivation for this?

**Comment by ElwynJohn** [comment]
I think this might result in cleaner code but what we've got is good so I would only make this change out of interest or if a future problem incentivises this change. I think the main reason it would make nicer code is that instead of having a bunch of conditionals, we could make use of polymorphism. We could talk about it a bit when your next online.

**Comment by ElwynJohn** [comment]
Most piece related logic is handled by the chess engine now so this no longer applies
