### ISSUE TITLE
Make the tile highlights prettier

### ISSUE THREAD

**Issue by rleathart** [ElwynJohn/Chess#32]
Change the colours in ChessTile to be prettier please :)

https://github.com/ElwynJohn/Chess/blob/27dc47c66b5eb64eb3042d52625ff8b9e10dac41/Chess/Models/ChessTile.cs#L60

**Comment by ElwynJohn** [comment]
The tile highlights are prettier now. Before closing this, I want to consider making the black tile colour slightly
